### ISSUE TITLE
Set currency from within VS Code?

### ISSUE THREAD

**Issue by Bouke** [infracost/vscode-infracost#120]
Hi, I've just started using Infracost. So far it is looking good and there are some estimates showing up in my terraform file. However I'm trying to change the currency (to EUR). The documentation mentions to run the `infracost` command, however I don't have that installed. I also fail to understand what this command will change to my repository. Is there some file I should add to my repo to change the currency, without having to install the command?

**Comment by hugorut** [comment]
Hi @Bouke, the VS Code extensions uses a bundled infracost CLI so you won't have that installed on your machine's PATH. In order to change the currency settings without downloading a CLI into your PATH you can edit the Infracost global configuration file at: `~/.config/infracost/configuration.yml`. If you add the following to that file:

```
version: "0.1"
currency: EUR
```

Then you should see prices displayed in euros.

**Comment by Bouke** [comment]
That's working, thank you!

**Comment by alikhajeh1** [comment]
@hugorut do we need to update https://github.com/infracost/vscode-infracost#how-can-i-configure-the-currency-infracost-uses ? if not, we can close this issue

**Comment by hugorut** [comment]
@alikhajeh1 sure I'll update
